In [10]:
import pandas as pd
from datetime import datetime
import re


def get_chat_dataframe(file):
    data = []

    with open(file, 'r', encoding='utf-8') as f:
        lines = f.read().split('\n\n')

        for i, line in enumerate(lines):
            try:
                time_logged = line.split('—')[0].strip()
                time_logged = datetime.strptime(time_logged, '%Y-%m-%d_%H:%M:%S')

                username_message = line.split('—')[1:]
                username_message = '—'.join(username_message).strip()

                username, channel, message = re.search(
                        ':(.*)\!.*@.*\.tmi\.twitch\.tv PRIVMSG #(.*) :(.*)', username_message
                ).groups()

                d = {
                    'dt': time_logged,
                    'channel': channel,
                    'username': username,
                    'message': message
                }

                data.append(d)

            except Exception as e:
                print(e)
                pass

    return pd.DataFrame().from_records(data)


df = get_chat_dataframe('chat_doublelift.log')

df.set_index('dt', inplace=True)

print(df.shape)

df.to_csv('./doublelift.csv')

df.head()

'NoneType' object has no attribute 'groups'
'NoneType' object has no attribute 'groups'
'NoneType' object has no attribute 'groups'
'NoneType' object has no attribute 'groups'
time data '' does not match format '%Y-%m-%d_%H:%M:%S'
(1797, 3)

                       channel            username     message
dt
2021-04-27 18:30:57  loltyler1            eric4211         Pog
2021-04-27 18:30:57  loltyler1  bestarcherconverge      HUGEEE
2021-04-27 18:30:57  loltyler1           raunosaul        kekw
2021-04-27 18:30:57  loltyler1          lovelypleb  BARON KEKW
2021-04-27 18:30:58  loltyler1         trashbunny_  BOBBY KEKW

In [11]:
df

,channel,username,message
dt,,,
2021-04-27 18:30:57,loltyler1,eric4211,Pog
2021-04-27 18:30:57,loltyler1,bestarcherconverge,HUGEEE
2021-04-27 18:30:57,loltyler1,raunosaul,kekw
2021-04-27 18:30:57,loltyler1,lovelypleb,BARON KEKW
2021-04-27 18:30:58,loltyler1,trashbunny_,BOBBY KEKW
...,...,...,...
2021-04-27 18:51:54,loltyler1,xsteezzy,KEKW
2021-04-27 18:51:56,loltyler1,bestarcherconverge,LUL
2021-04-27 18:51:57,loltyler1,horsesaredumb,EHEHE AYAYA
2021-04-27 18:51:59,loltyler1,mayooi_,AYAYA 7
2021-04-27 18:52:00,loltyler1,trexjohnson10,@thatfknguy how does it feel to be a dirty fuc...